sudo: false
dist: xenial

language: rust
cache:
  - cargo
  - npm

script:
  - cargo build --verbose
  - cargo test --verbose
  - make

rust:
  - nightly
  - beta
  - stable

matrix:
  allow_failures:
    - rust: nightly
