[package]
authors = ["Chris West (Faux) <git@goeswhere.com>"]
name = "quad-image"
version = "0.1.0"

[dependencies]
error-chain = "0.11"
image = "0.18"
iron = "~0.6"
params = "~0.8"
rand = "0"
router = "~0.6"
tempfile = "2"
[profile.release]
lto = true
