[package]
authors = ["Chris West (Faux) <git@goeswhere.com>"]
name = "quad-image"
version = "0.1.0"

[dependencies]
base64 = "0.9"
failure = "0.1"
hmac = "0.7"
lazy_static = "1"
libc = "0.2"
rand = "0.5"
regex = "1"
rouille = "2.2"
serde_json = "1"
sha2 = "0.8"
tempfile-fast = "0.2"

[dependencies.image]
version = "0.20"
# features -= "hdr", "dxt", "jpeg_rayon"
default-features = false
features = ["gif_codec", "jpeg", "ico", "png_codec", "pnm", "tga", "tiff", "webp", "bmp"]

[dependencies.rusqlite]
version = "0.15"
features = ["bundled"]

[dev-dependencies]
tempdir = "0.3"

[profile.release]
lto = true
