[package]
authors = ["Chris West (Faux) <git@goeswhere.com>"]
name = "quad-image"
version = "0.1.0"

[dependencies]
error-chain = "0.11"
image = "0.19"
iron = "~0.6"
libc = "0.2"
params = "~0.8"
rand = "0.4"
router = "~0.6"
tempfile-fast = "0.2"

[dev-dependencies]
tempdir = "0.3"

[profile.release]
lto = true
