[package]
authors = ["Chris West (Faux) <git@goeswhere.com>"]
name = "quad-image"
version = "0.1.0"

[dependencies]
error-chain = "0.11"
image = "0"
iron = "~0.5"
params = "~0.6"
rand = "0"
router = "~0.5"
tempfile-fast = "0.1"
[profile.release]
lto = true
